### ISSUE TITLE
Login gives error

### ISSUE THREAD

**Issue by maarteNNNN** [elitan/hasura-backend-plus#37]
Trying to login with a registered user i get the following output from the logs:
```
hasura-backend-plus_1  | user: {
hasura-backend-plus_1  |   "id": 1,
hasura-backend-plus_1  |   "password": "$2a$10$WiMG2bz7Vnkv0cMLdn4i1.9LCNEPtixGOYv.DBYDmxt3aDoQ0KiEm",
hasura-backend-plus_1  |   "active": true,
hasura-backend-plus_1  |   "default_role": "user",
hasura-backend-plus_1  |   "roles": []
hasura-backend-plus_1  | }
hasura-backend-plus_1  | Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
hasura-backend-plus_1  |     at Sign.sign (internal/crypto/sig.js:80:26)
hasura-backend-plus_1  |     at Object.sign (/app/node_modules/jwa/index.js:76:45)
hasura-backend-plus_1  |     at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)
hasura-backend-plus_1  |     at Object.module.exports [as sign] (/app/node_modules/jsonwebtoken/sign.js:198:16)
hasura-backend-plus_1  |     at Object.generateJwtToken (/app/src/auth/auth-tools.js:25:16)
hasura-backend-plus_1  |     at router.post (/app/src/auth/auth.js:306:32)
```
I know it has something to do with the keys. I generated the keys from  the terminal using:
```
ssh-keygen -t rsa -b 4096 -m PEM -f jwtRS256.key
openssl rsa -in jwtRS256.key -pubout -outform PEM -out jwtRS256.key.pub
```
tried to verify the signature at jwt.io and it was a valid signature. Seeing the hasura-backend minio example it shows that both need to be the public keys. What am I doing wrong?

**Comment by elitan** [comment]
How does your docker-compose.yaml look like? I am thinking of this line:

`HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "secret_key"}'`

**Comment by maarteNNNN** [comment]
With the standard env: `HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "secret_key"}'`
The setup works however using:
```
HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256", "key":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsTgTtIyINnO2Kr2uFp9J\n/a/V0W2BtCFR1Q+w77CUVg+N+coyutPKyZ8EZe87ggJkIGBeJZiQk4haRucdfC6x\nU/DwKLg0AkmzADW4dfGkZX4zIuSpgxDpW52lPRvcr5TnJLsw+yzlNbqHafcwQA6Z\nuiY4LyJw7LbR8rTFLYBY/QF2MBWhuCJe/t4e5knSCWUUDgOSlWY0p4qr3jrEeBAP\nqBffV3pUFKFbnF2Ig9veOY+hluTy+hKgNp8alroXR9S5magnNCWq/n+pha/NIht1\nZfzpxL3gqm/crlIlXRFn/jQjFev3jS/zRCbLbwvL54PqSCp0IoYzxVhYK27By1mu\nEAA9+GpRMexcpyR0Q0bFrkAMONHCJyyNFfrMm+jAU1M/4bxWfLfjCuIHLb03hPD0\nlHrumum9lu8WPRvAoQvXD4aEYhArRX1XI/o5OCDOG5X8pAN5jT7pBr/KqORf0327\nDe1s9WB4sR0fnRsF+zoADOTmkrO/QlRF19gjBSs9WxYuBuUPDTgY5UtjYz8nGpxB\nPMbiAaeR6zGQMStGhnL0R560Gp/gOd7nodAqVALb00+K5fuiFfrPK6Ze5+zv6urW\nnG5viSVe5laS5sgbGrWT1OrjujbqHGVLOXZDfsjySCOuCtiNWLd2+ePRfFFZgPHR\nPvddFP0hRzPFXPYkX4a/WBkCAwEAAQ==\n-----END PUBLIC KEY-----"}'
```
It doesn't work. Should I just generate a random secret? Like: `ihoqsfhifpsdQDFSQGihsqdgjlsqhgoishqgSDGheroigheriugsduifgsdiufhigDSFgdugsduf`?

**Comment by elitan** [comment]
Yes that is what I have done. I have not experimented with other formats.

**Comment by maarteNNNN** [comment]
@elitan I was a bit confused seeing the minio example in the repo which contained a RS256 generated key. Do you want me to make a pull request and change the `docker-compose.yaml`?

**Comment by elitan** [comment]
Yes please do! Just make sure to test if befor you make a pull request.
Thanks!
