### ISSUE TITLE
/auth/logout throw an error

### ISSUE THREAD

**Issue by makstr** [elitan/hasura-backend-plus#74]
Hi, just noticed there is a reference to undefined user variable in the /auth/logout route, the logout-all is ok

```
router.post('/logout', async (req, res, next) => {
  // get refresh token
  const schema = Joi.object().keys({
    refresh_token: Joi.string().uuid().required(),
  });

  const { error, value } = schema.validate(req.body);

  const { refresh_token } = value;

  // delete refresh token passed in data
  let mutation = `
  mutation (
    $refresh_token: uuid!,
  ) {
    delete_refresh_token: delete_${schema_name}refresh_tokens (
      where: {
        refresh_token: { _eq: $refresh_token }
      }
    ) {
      affected_rows
    }
  }
  `;

  let hasura_data;
  try {
    hasura_data = await graphql_client.request(mutation, {
      user_id: user.id,
    });
  } catch (e) {
    console.error(e);
    // console.error('Error connection to GraphQL');
    return next(Boom.unauthorized('Unable to delete refresh token'));
  }

  res.send('OK');
});
```

```
hasura-backend-plus_1  | POST /auth/logout 401 84 - 5.430 ms
hasura-backend-plus_1  | ReferenceError: user is not defined
hasura-backend-plus_1  |     at router.post (/app/src/auth/auth.js:166:16)
hasura-backend-plus_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hasura-backend-plus_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
hasura-backend-plus_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
hasura-backend-plus_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hasura-backend-plus_1  |     at /app/node_modules/express/lib/router/index.js:281:22
hasura-backend-plus_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
hasura-backend-plus_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
hasura-backend-plus_1  |     at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
hasura-backend-plus_1  |     at router (/app/node_modules/express/lib/router/index.js:47:12)
hasura-backend-plus_1  | Unable to delete refresh token
hasura-backend-plus_1  | Error: Unable to delete refresh token
hasura-backend-plus_1  |     at router.post (/app/src/auth/auth.js:171:22)
hasura-backend-plus_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hasura-backend-plus_1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
hasura-backend-plus_1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
hasura-backend-plus_1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
hasura-backend-plus_1  |     at /app/node_modules/express/lib/router/index.js:281:22
hasura-backend-plus_1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
hasura-backend-plus_1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
hasura-backend-plus_1  |     at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
hasura-backend-plus_1  |     at router (/app/node_modules/express/lib/router/index.js:47:12)```

**Comment by elitan** [comment]
Thanks. Fixed today.
