### ISSUE TITLE
Unable to log in.

### ISSUE THREAD

**Issue by KJDEV-PL** [elitan/hasura-backend-plus#76]
When trying to log in there is an error:

`Error: error:0909006C:PEM routines:get_name:no start line

    at Sign.sign (internal/crypto/sig.js:80:26)

    at Object.sign (/app/node_modules/jwa/index.js:76:45)

    at Object.jwsSign [as sign] (/app/node_modules/jws/lib/sign-stream.js:32:24)

    at Object.module.exports [as sign] (/app/node_modules/jsonwebtoken/sign.js:198:16)

    at Object.generateJwtToken (/app/src/auth/auth-functions.js:26:16)

    at router.post (/app/src/auth/local.js:252:36)

POST /auth/local/login - - - - ms`

**Comment by KJDEV-PL** [comment]
Ok, I was able to solve the problem.
It helped me:

> HASURA_GRAPHQL_JWT_SECRET: {"type":"HS256", "key": "qwertyuiopasdfghjklzxcvbnmqwertyuiop"}
