### ISSUE TITLE
storage upload responds with 200 even if no file was sent for upload

### ISSUE THREAD

**Issue by KJDEV-PL** [elitan/hasura-backend-plus#77]
Someone will tell me what is wrong?

[docker-compose](https://pastebin.pl/view/65c62dba)

> root@vps75XXXX:/HASURA# ls
db_data  docker-compose.yaml  minio_volume  pgadmin_files  storage-rules

> root@vps752248:/HASURA/storage-rules# ls
index.js

[index.js](https://pastebin.pl/view/e2b08f80)

I'm using Postman: 
> POST http://54.XX.XXX.66:1010/storage/upload

HB+ logs show:
> POST /storage/upload 200 - - 0.683 ms

No files can be seen on minio server.

**Comment by elitan** [comment]
I think what's happening is you are sending the file in a way HBP does not expect.

So HBP responds with, 200 OK even if it did not upload any file. This behaviour should change. If no file is being sent, HBP should respond with http status code 400.

![Screenshot 2019-11-27 at 17 31 16](https://user-images.githubusercontent.com/331818/69741666-c095b200-113b-11ea-88b2-394c0a0e65f3.png)
![Screenshot 2019-11-27 at 17 31 19](https://user-images.githubusercontent.com/331818/69741667-c12e4880-113b-11ea-811f-c8241bb96055.png)

**Comment by KJDEV-PL** [comment]
**What can it be about?**

`Unexpected field


MulterError: Unexpected field


    at wrappedFileFilter (/app/node_modules/multer/index.js:40:19)


    at Busboy.<anonymous> (/app/node_modules/multer/lib/make-middleware.js:114:7)


    at Busboy.emit (events.js:198:13)


    at Busboy.EventEmitter.emit (domain.js:448:20)


    at Busboy.emit (/app/node_modules/busboy/lib/main.js:38:33)


    at PartStream.<anonymous> (/app/node_modules/busboy/lib/types/multipart.js:213:13)


    at PartStream.emit (events.js:198:13)


    at PartStream.EventEmitter.emit (domain.js:448:20)


    at HeaderParser.<anonymous> (/app/node_modules/dicer/lib/Dicer.js:51:16)


    at HeaderParser.emit (events.js:198:13)


POST /storage/upload 500 948 - 641.566 ms


TypeError: Cannot read property 'statusCode' of undefined


    at app.use (/app/src/index.js:74:32)


    at Layer.handle_error (/app/node_modules/express/lib/router/layer.js:71:5)


    at trim_prefix (/app/node_modules/express/lib/router/index.js:315:13)


    at /app/node_modules/express/lib/router/index.js:284:7


    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)


    at Immediate.next (/app/node_modules/express/lib/router/index.js:275:10)


    at Immediate.<anonymous> (/app/node_modules/express/lib/router/index.js:635:15)


    at runCallback (timers.js:706:11)


    at tryOnImmediate (timers.js:676:5)


    at processImmediate (timers.js:658:5)`

**Comment by elitan** [comment]
That's probably an error not handled correctly. How can I reproduce this error?

**Comment by MarcelloTheArcane** [comment]
I have been getting that error intermittently too. Normally a refresh clears it.

**Comment by KJDEV-PL** [comment]
Very strange.
I haven't changed anything and it works today.
